# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/build ./build
# Copy production dependencies
COPY --from=builder /app/node_modules ./node_modules
# Copy other necessary files if any

ENTRYPOINT ["node", "build/index.js"]
